version: "3.8"

services:

  db_projeto02:
    container_name: database_projeto02
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=projeto02_database
    volumes:
      - pgdata:/data/postgresql

  app:
    build: .
    container_name: projeto02
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - db_projeto02
    depends_on:
      - db_projeto02

volumes:
  pgdata:
    driver: local
